# Generated by Django 4.2.2 on 2025-05-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
