# Generated by Django 4.2.2 on 2025-05-26 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todopriority',
            name='user',
        ),
        migrations.RemoveField(
            model_name='todostatus',
            name='user',
        ),
    ]
